Working live migration of replicated volumes

diff --git a/remotes/tm/vdc/ln b/remotes/tm/vdc/ln
--- a/remotes/tm/vdc/ln
+++ b/remotes/tm/vdc/ln
@@ -23,9 +23,8 @@ VMID=$3
 DSID=$4
 
 tool="${ROOT}/hooks/vdc/tool.py"
-conf="${ROOT}/hooks/vdc/mkconfig.py"
-gids="${ROOT}/hooks/vdc/get_image_ids.py"
 vdc="${ROOT}/../vdc-nebula/remotes/binaries"
+conf="${ROOT}/hooks/vdc/mkconfig.py"
 vdctool="$vdc/vdc-tool"
 
 vdc_log "=> LN ($1) ($2) ($3) ($4)"
@@ -33,39 +32,24 @@ vdc_log "=> LN ($1) ($2) ($3) ($4)"
 DST_PATH=`arg_path $DST`
 DST_HOST=`arg_host $DST`
 DST_DIR=`dirname $DST_PATH`
-SRC_ARG_PATH=`arg_path $SRC`
 
-DST_DS_PATH="$(dirname $(dirname $(dirname $DST_PATH)))"
-SRC_DS_PATH="$(dirname $(dirname $SRC_ARG_PATH))"
-SRC_PATH="${DST_DS_PATH}${SRC_ARG_PATH##$SRC_DS_PATH}"
-
-vdc_log "${gids} $VMID ${SRC_PATH}"
-${gids} $VMID "${SRC_PATH}" > /tmp/debug 2>&1
-eval `${gids} $VMID "${SRC_PATH}"`
-vdc_log "Set NAME to ${CACHE} for $VMID"
-vdc_log "Set IGNORE to $IGNORE for $VMID"
-vdc_log `${gids} $VMID`
+vdc_log "${tool} env ${VMID} ${DSID} ${DST_HOST} ${SRC}"
+vdc_log "=> `${tool} env ${VMID} ${DSID} ${DST_HOST} ${SRC}`"
+eval `${tool} env ${VMID} ${DSID} ${DST_HOST} ${SRC}`
 
 vdcstore="sudo /bin/bash -c 'ulimit -c unlimited && exec $vdc/vdc-store -n ${CACHE}'"
 
 vdc_log "Make Path ($DST_HOST) ($DST_DIR)"
 ssh_make_path $DST_HOST $DST_DIR
 
-CACHE_SIZE="none"
-CACHE_LVM="none"
-DS_NAME="none"
-
-vdc_log "${tool} ln $VMID $DSID $DST_HOST"
-vdc_log "[`${tool} ln $VMID $DSID $DST_HOST`]"
-eval `${tool} ln $VMID $DSID $DST_HOST`
-
-execute ${DS_NAME} ${conf} "Error Updating VDC Server Config"
-
 #if [ "${IS_REPLICA}" == "YES" ] ; then
+#    execute ${DS_NAME} ${conf} "Error Updating VDC Server Config"
 #    execute $DST_HOST "sudo $vdctool -n ${CACHE} --add vdc:${DS_NAME}/${STORE}" "Error adding replica"
-#    vdc_log "Exit code was: ($$) ($?)"
-#    exit 0
+#    vdc_log "Exit code was: ($?)"
+#    exit $?
 #fi
+
+execute ${DS_NAME} "sudo ${conf}" "Error Updating VDC Server Config"
 
 vdc_log "* REPLICA_ID is (${REPLICA_ID})"
 
@@ -75,7 +59,34 @@ execute $DST_HOST "cd ${DST_DIR}; rm -f ${DST_PATH}; ln -s /dev/vdc/mapper/${CAC
 
 if [ ! "${REPLICA_ID}" == "none" ]
 then
+    execute ${REPLICA_DS} "sudo ${conf}" "Error Updating VDC Server Config"
     execute $DST_HOST "sudo $vdctool -n ${CACHE} --add vdc:${REPLICA_DS}/${REPLICA_STORE}" "Error adding replica"
 fi
 
 exit 0
+
+
+
+
+#SRC_ARG_PATH=`arg_path $SRC`
+#DST_DS_PATH="$(dirname $(dirname $(dirname $DST_PATH)))"
+#SRC_DS_PATH="$(dirname $(dirname $SRC_ARG_PATH))"
+#SRC_PATH="${DST_DS_PATH}${SRC_ARG_PATH##$SRC_DS_PATH}"
+#vdc_log "${gids} $VMID ${SRC_PATH}"
+#${gids} $VMID "${SRC_PATH}" > /tmp/debug 2>&1
+#eval `${gids} $VMID "${SRC_PATH}"`
+#vdc_log "Set NAME to ${CACHE} for $VMID"
+#vdc_log "Set IGNORE to $IGNORE for $VMID"
+#vdc_log `${gids} $VMID`
+#conf="${ROOT}/hooks/vdc/mkconfig.py"
+#gids="${ROOT}/hooks/vdc/get_image_ids.py"
+#CACHE_SIZE="none"
+#CACHE_LVM="none"
+#DS_NAME="none"
+#REPLICA_ID="none"
+
+#vdc_log "${tool} ln $VMID $DSID $DST_HOST"
+#vdc_log "[`${tool} ln $VMID $DSID $DST_HOST`]"
+#eval `${tool} ln $VMID $DSID $DST_HOST`
+
+#execute ${DS_NAME} ${conf} "Error Updating VDC Server Config"
