Reworking for replicas

diff --git a/remotes/tm/vdc/ln b/remotes/tm/vdc/ln
--- a/remotes/tm/vdc/ln
+++ b/remotes/tm/vdc/ln
@@ -28,16 +28,7 @@ gids="${ROOT}/hooks/vdc/get_image_ids.py"
 vdc="${ROOT}/../vdc-nebula/remotes/binaries"
 vdctool="$vdc/vdc-tool"
 
-eval `${gids} $VMID`
-
-vdc_log "Set NAME to $NAME for $VMID"
-vdc_log `${gids} $VMID`
-
-vdcstore="sudo /bin/bash -c 'ulimit -c unlimited && exec $vdc/vdc-store -n $NAME'"
-
-CACHE_SIZE="none"
-CACHE_LVM="none"
-DS_NAME="none"
+vdc_log "=> LN ($1) ($2) ($3) ($4)"
 
 DST_PATH=`arg_path $DST`
 DST_HOST=`arg_host $DST`
@@ -48,16 +39,43 @@ DST_DS_PATH="$(dirname $(dirname $(dirname $DST_PATH)))"
 SRC_DS_PATH="$(dirname $(dirname $SRC_ARG_PATH))"
 SRC_PATH="${DST_DS_PATH}${SRC_ARG_PATH##$SRC_DS_PATH}"
 
+vdc_log "${gids} $VMID ${SRC_PATH}"
+${gids} $VMID "${SRC_PATH}" > /tmp/debug 2>&1
+eval `${gids} $VMID "${SRC_PATH}"`
+vdc_log "Set NAME to ${CACHE} for $VMID"
+vdc_log "Set IGNORE to $IGNORE for $VMID"
+vdc_log `${gids} $VMID`
+
+vdcstore="sudo /bin/bash -c 'ulimit -c unlimited && exec $vdc/vdc-store -n ${CACHE}'"
+
 vdc_log "Make Path ($DST_HOST) ($DST_DIR)"
 ssh_make_path $DST_HOST $DST_DIR
+
+CACHE_SIZE="none"
+CACHE_LVM="none"
+DS_NAME="none"
 
 vdc_log "${tool} ln $VMID $DSID $DST_HOST"
 vdc_log "[`${tool} ln $VMID $DSID $DST_HOST`]"
 eval `${tool} ln $VMID $DSID $DST_HOST`
 
 execute ${DS_NAME} ${conf} "Error Updating VDC Server Config"
-execute $DST_HOST "sudo $vdctool -n  ${NAME} --create -c${CACHE_SIZE} --nonpersist lvm:${CACHE_LVM}/${NAME} vdc:${DS_NAME}/${NAME}" "Error creating Cache"
+
+#if [ "${IS_REPLICA}" == "YES" ] ; then
+#    execute $DST_HOST "sudo $vdctool -n ${CACHE} --add vdc:${DS_NAME}/${STORE}" "Error adding replica"
+#    vdc_log "Exit code was: ($$) ($?)"
+#    exit 0
+#fi
+
+vdc_log "* REPLICA_ID is (${REPLICA_ID})"
+
+execute $DST_HOST "sudo $vdctool -n  ${CACHE} --create -c${CACHE_SIZE} --nonpersist lvm:${CACHE_LVM}/${CACHE} vdc:${DS_NAME}/${STORE}" "Error creating Cache"
 execute $DST_HOST "$vdcstore" "Error starting VDC"
-#execute $DST_HOST "sudo $vdctool  -n ${NAME} --wait STARTED" "Failed waiting on vdc-start"
-execute $DST_HOST "cd ${DST_DIR}; rm -f ${DST_PATH}; ln -s /dev/vdc/mapper/${NAME} ${DST_PATH}" "Error linking ${DST_PATH} to /dev/vdc/mapper/${NAME}" "Error linking ${DST_PATH} to /dev/vdc/mapper/${NAME}"
+execute $DST_HOST "cd ${DST_DIR}; rm -f ${DST_PATH}; ln -s /dev/vdc/mapper/${CACHE} ${DST_PATH}" "Error linking ${DST_PATH} to /dev/vdc/mapper/${CACHE}" "Error linking ${DST_PATH} to /dev/vdc/mapper/${CACHE}"
+
+if [ ! "${REPLICA_ID}" == "none" ]
+then
+    execute $DST_HOST "sudo $vdctool -n ${CACHE} --add vdc:${REPLICA_DS}/${REPLICA_STORE}" "Error adding replica"
+fi
+
 exit 0
